# Generated by Django 4.0.8 on 2022-12-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_megusta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megusta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producto'),
        ),
    ]
